### ISSUE TITLE
Settings not opening

### ISSUE THREAD

**Issue by ghost** [pop-os/gnome-control-center#108]
Hi, when I try to open settings it doesn't do anything other than load a few seconds.
I tried opening through the main menu, the sound widget and the command line.
From the command line I got conflicting debug information: 

When launching with "gnome-control-center": 
```
(gnome-control-center:3789): GLib-GIO-ERROR **: 10:40:20.250: Settings schema 'org.gnome.gedit.preferences.editor' is not installed
Trace/breakpoint trap (core dumped)

```

But then when I try installing it with "sud apt install gnome-control-center":
```
sudo apt install gnome-control-center
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnome-control-center is already the newest version (1:3.36.3-0ubuntu1pop1~1595273700~20.04~034354a).
gnome-control-center set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

This may or may not be a direct bug, but I guess I'll report it.
Any troubleshooting information is appreciated.
I can also provide further information if needed, tho I'm unsure what other information would be of value here so I'm not just gonna dump a bunch of additional stuff without request

**Comment by jacobgkau** [comment]
I believe this is related to https://github.com/pop-os/desktop/pull/51. Gedit was moved from depends to recommends, which means it's able to be removed. I'm able to reproduce this issue after removing `gedit-common`, which is a dependency of `gedit`. (It doesn't get removed right away when removing `gedit`, it remains installed until the next time `apt autoremove` is run, which may be why this wasn't caught during testing.)

The issue only affects the Appearance page of GNOME Control Center, likely because of the light/dark mode switcher. However, once a user clicks on that page once, GNOME Control Center will continue trying to open that page when it's started.

`gedit-common` only recommends `gedit`, and GNOME Control Center still seems to function after removing `gedit` as long as `gedit-common` is still present, so you can fix this with `sudo apt install gedit-common`. We will either need to add `gedit-common` to `pop-desktop`'s depends, move `gedit` from recommends back to depends, or make the light/dark mode switcher not crash when `gedit-common` is missing.

**Comment by mmstick** [comment]
Gio has this terrible concept of crashing when a schema does not exist. Patching the theme switcher to check for the schema and then rebuilding gnome-control-center would be ideal.

**Comment by ids1024** [comment]
> Gio has this terrible concept of crashing when a schema does not exist.

Hm, yes. It should return some kind of error, so the program can crash if appropriate, or handle it. But I guess they didn't design it that way because C programs probably wouldn't end up checking the error value...

Do you know a good way to check that the schema exists? I don't see a function like that in the [GSettings API](https://developer.gnome.org/gio/stable/GSettings.html).

**Comment by mmstick** [comment]
@ids1024 I have a [function for that in our gtk_extras crate](https://github.com/pop-os/gtk-extras/blob/c55eb63bd92126206bd6ded2708a7cd869688822/src/functions/settings.rs#L37:L59)

**Comment by ghost** [comment]
It was fixed during todays update of gnome settings

**Comment by fkruczek** [comment]
in case someone still has problems with it - this helped me:

```
sudo apt-get remove gnome-control-center

sudo apt-get remove gnome-control-center-data

sudo apt install gnome-control-center

gnome-control-center
```
